project:
  type: website # https://icons.getbootstrap.com/
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  title: "Libby Heeren"
  description: "Data Science, R community, statistics, human connection."
  site-url: https://libbyheeren.com
  repo-url: https://github.com/LibbyHeeren/libby_website
  repo-actions:
    - source
    - issue
  favicon: assets/img/LIBS-favicon.png
  # twitter-card:
  #   creator: "@jadeynryan"
  #   image: assets/img/JR-logo-white-bg.png
  #   image-alt: "Cat with tail shaped as the letter J next to last name initial R"
  # open-graph:
  #   locale: en_EN
  #   image: assets/img/JR-logo-white-bg.png
  #   image-alt: "Cat with tail shaped as the letter J next to last name initial R"
  page-navigation: true
  google-analytics:
    tracking-id: "G-ZEZYBFE5EF"
    anonymize-ip: true
  cookie-consent:
    type: express
    prefs-text: "Change cookies 🍪"

  navbar:
    pinned: true
    logo: assets/img/book-vivid.png
    logo-alt: "Open book with magical golden sparkles and pink light radiating from it"
    left:
      - text: About
        icon: bi-stars
        href: index.qmd
      # - text: CV
      #   icon: file-earmark-text-fill
      #   aria-label: cv
      #   href: cv.qmd
      - text: Blog
        icon: book-fill
        aria-label: blog
        href: blog.qmd
      # - text: Talks
      #   aria-label: talks
      #   icon: mic-fill
      #   href: talks.qmd
      # - text: Projects
      #   icon: puzzle-fill
      #   aria-label: projects
      #   href: projects.qmd
      - text: Data Humans Podcast
        icon: mic-fill
        href: podcast.qmd
    tools:
      # - icon: rss
      #   aria-label: rss
      #   href: blog.xml
      - icon: github
        aria-label: Git Hub
        href: https://github.com/LibbyHeeren
      - icon: linkedin
        aria-label: Linked In
        href: https://www.linkedin.com/in/libbyheeren/
      - icon: mastodon
        aria-label: Mastodon
        href: https://data-folks.masto.host/@libby

  page-footer:
    border: true
    left: "&#169; 2023 Libby Heeren"
    center:
      - text: Code of conduct
        href: coc.qmd
      - text: Accessibility
        href: accessibility.qmd
      - text: License
        href: license.qmd
    right: "made with {{< fa heart title='love' aria-hidden='true' >}} & [Quarto](https://quarto.org)"

format:
  html:
    theme: [flatly, assets/styling/theme.scss]
    toc: true
    toc-depth: 4
    pagetitle: "Libby Heeren | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y

