project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

title-meta: "Jadey Ryan"
description-meta: "Jadey's personal website for her portfolio, blog, and shop. Explore for R coding, cats, and environmental data science content."

website:
  title: "Jadey Ryan"
  description: "Jadey's personal website for her portfolio, blog, and shop. Explore for R coding, cats, and environmental data science content."
  site-url: https://jadeynryan.com
  favicon: assets/img/JR-favicon.svg
  twitter-card:
    image: assets/img/JR-favicon.svg
    image-alt: "cat with tail shaped as the letter J next to last name initial R"
  open-graph:
    locale: en_EN
    site-name: Jadey Ryan
    image: assets/img/JR-favicon.svg
    image-alt: "cat with tail shaped as the letter J next to last name initial R"
  page-navigation: true
  google-analytics:
    tracking-id: "G-LEVV3VZT0E"
    anonymize-ip: true
  cookie-consent:
    type: express
    prefs-text: "Change Cookies 🍪"

  navbar:
    pinned: true
    logo: assets/img/JR-logo-white.svg
    logo-alt: "cat with tail shaped as the letter J next to last name initial R"
    left:
      - text: About
        icon: person-circle
        aria-label: about me
        href: index.qmd
      - text: CV
        icon: file-earmark-text-fill
        aria-label: cv
        href: cv.qmd
      - text: Blog
        icon: pen-fill
        aria-label: blog
        href: blog.qmd
      - text: Talks
        aria-label: talks
        icon: mic-fill
        href: talks.qmd
      - text: Projects
        icon: puzzle-fill
        aria-label: projects
        href: projects.qmd
      - text: the coding cats shop
        icon: bag-heart-fill
        aria-label: the coding cats shop
        href: shop.qmd
    tools:
      - icon: github
        aria-label: GitHub
        href: https://github.com/jadeynryan
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/jadeynryan/
      - icon: mastodon
        aria-label: Mastodon
        href: https://fosstodon.org/@jadeynryan

  page-footer:
    border: true
    left: "&#169; 2023 Jadey Ryan"
    center:
      - text: Accessibility
        aria-label: accessibility
        href: accessibility.qmd
      - text: License
        aria-label: license
        href: license.qmd
    right: "made with {{< fa heart title='love' aria-hidden='true' >}} & [Quarto](https://quarto.org)"

format:
  html:
    theme: [flatly, assets/scss/theme.scss]
    toc: true
    pagetitle: "Jadey Ryan | {{< meta title >}}"
    page-layout: full
    highlight-style: a11y
    smooth-scroll: true
    code-link: true
    link-external-newwindow: true


